title: User Guide
brand: Bookingpad
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The most advanced NDC-ready booking tool for travel agents
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://user-guide.bookingpad.net/" # the base hostname & protocol for your site, e.g. http://example.com

algolia:
  application_id: N1HTGKTL3T
  index_name: userguide
  search_only_api_key: 7e7721c213f1245daa4bd287d5586f87

collections:
  bookingpad_docs:
    permalink: "/:collection/:path/"
    output: true
  agencyportal_docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/posts/:year/:month/:day/:title/"
    output: false
  category:
    output: true

twitter_username: AirGateway
github_username:  AirGateway

show_dir_listing    : false

# Build settings
# theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
