backend:
  name: git-gateway
  branch: master
media_folder: 'assets/uploads'
collections:
  - name: 'Bookingpad Docs'
    label: 'Bookingpad Doc'
    folder: '_bookingpad_docs/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'doc-bp' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'bookingpad' }
      - label: "Sub-category"
        name: "sub_category"
        widget: "select"
        options:
          - { label: "Overview", value: "overview" }
          - { label: "Shopping & Booking", value: "shopping-booking" }
          - { label: "Order Management & Servicing", value: "order-management-servicing" }
          - { label: "Corporates & Traveler Profiles Management", value: "profile-management" }
          - { label: "Third-Parties", value: "third-parties" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'Agency Portal Docs'
    label: 'Agency Portal Doc'
    folder: '_agency_portal_docs/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'doc-ap' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'agency_portal' }
      - label: "Sub-category"
        name: "sub_category"
        widget: "select"
        options:
          - { label: "Overview", value: "ap_overview" }
          - { label: "Managing Agents", value: "manage-agents" }
          - { label: "Managing Partners", value: "manage-partners" }
          - { label: "Managing Developers", value: "manage-developers" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
